---
title: Cluster Analysis
output: github_document
---

```{r}
install.packages("tidyverse")
install.packages("cluster")
install.packages("fpc")
install.packages("factoextra")
install.packages("janitor")

library(tidyverse)
library(cluster)
library(fpc)
library("factoextra")
library("janitor")
```

## R Markdown


```{r}
#create data frame
jobdf <- read.csv("Employees.csv")
View(jobdf)
set.seed(42)



```


```{r}
#name new data frame without non-continuous data points (variables of interest)
quantdf <- jobdf[c(1,16,20,25)]
View(quantdf)

#normalize each variable
quantdfn <- scale(quantdf)
View(quantdfn)

#set number of seed in order to replicate the analysis
set.seed(42)

#create a function to calculate total within-cluster sum of squared deviations
#to use in elbow plot
wss <- function(k){kmeans(quantdfn, k, nstart=10)} $tot.withinss

#range of k values for elbow plot 
k_values <- 1:10


#run the function to create the range of values for the elbow plot
wss_values <- map_dbl(k_values, wss)

#create a new data frame containing both k_values and wss_values
elbowdf <- data.frame(k_values, wss_values)

#graph the elbow plot
ggplot(elbowdf, mapping = aes(x = k_values, y = wss_values)) +
  #lines and points
  geom_line() + geom_point()

#run k-means clustering with 4 clusters (k=4) and 1000 random restarts
k4 <- kmeans(quantdfn, 4, nstart =1000)

#display structure of the k-means clustering object
str(k4)

#display info on k means clustering
k4


#display cluster statistics
cluster.stats(dist(quantdfn, method = "euclidean"), k4$cluster)
#focus on , average.distance for within, and
#longer distances are better for  between cluster distance of ave.between.matrix
#(smaller number is tigher grouping)


#combining each observation's cluster assignment with unscaled data frame
quantdfk4 <- cbind(quantdf, clusterID=k4$cluster)
View(quantdfk4)


#write data frame to CSV file to analyze excel
write.csv(quantdfk4, "magazine_kmeans_4clusters.csv")

#calculate variable averages for all non-normalized observations
summarize_all(quantdfk4, mean)

#calculate variable averages for each cluster
quantdfk4 %>%
  group_by(clusterID) %>%
  summarize_all(mean)

avg_salary <- mean(quantdfk4$MonthlyIncome)




```

```{r}


#set number of seed in order to replicate the analysis
set.seed(42)
View(quantdf)

#normalize data 
quantdfn <- scale(quantdf)
View(quantdfn)


#Calculate distance between each pair of observations using the dist function 
#and manhattan distance
match_dist <- dist(quantdfn, method="euclidean")

#run hierarchical clustering with the hclust function and group average linkage
cl_match_avg <- hclust(match_dist, method="ward.D")

#plot the dendrogram
plot(cl_match_avg)

#create 4 clusters using the cutree function
cl_match_avg_4 <- cutree(cl_match_avg, k=4)

#display vector of cluster assignments for each observation
cl_match_avg_4

#visualize clusters on the dendrogram
rect.hclust(cl_match_avg, k=4, border=2:4)

#link cluster assignments to original categorical data frame
hcl4df <- cbind(bindf, clusterID=cl_match_avg_4)

#calculate variable averages for all non-normalized observations
summarize_all(bindf, mean)

#calculate variable averages for each cluster
hcl4df %>%
  group_by(clusterID) %>%
  summarize_all(mean)

#display number of observations in each cluster
hcl4df %>%
  group_by(clusterID) %>%
  summarize(n())

# This tells you means of clusters. 
summarize_all(hcl4df, mean)




```


